apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    name: todo-app

---
apiVersion: v1
kind: Pod
metadata:
  name: todo-pod
  namespace: todo-app
  labels:
    app: todo-app
spec:
  containers:
    - name: todo-container
      image: abhinav0101/my-todo-app-django
      ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: todo-app
